Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
bfig = plotting.figure(plot_width=850, plot_height=300, title=f"Detrended Lightcurve (TIC{tic_id})")

# Short cadence
bfig.circle(short_cad_lc["TIME"], short_cad_lc["RAW_FLUX"]/np.median(short_cad_lc["RAW_FLUX"]), fill_color="black",size=2, line_color=None)
bfig.line(short_cad_lc["TIME"], short_cad_lc["RAW_FLUX"]/np.median(short_cad_lc["RAW_FLUX"]), line_color='black')

# Long cadence
bfig.circle(long_cad_lc["TIME"],long_cad_lc["SAP_FLUX"], fill_color="#0384f7",size=6, line_color=None)
bfig.line(long_cad_lc["TIME"],long_cad_lc["SAP_FLUX"], line_color='#0384f7')

# Marking the flare (tpeak is in BJD, while the time column in the light curve is BTJD, so we must convert)
vline = Span(location=(tpeak - 2457000), dimension='height', line_color='#bf006e', line_width=3)
bfig.renderers.extend([vline])

# Labeling the axes
bfig.xaxis.axis_label = "Time (BTJD)"
bfig.yaxis.axis_label = "Flux"

plotting.show(bfig)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[10], line 1[0m
[0;32m----> 1[0m bfig [38;5;241m=[39m [43mplotting[49m[38;5;241;43m.[39;49m[43mfigure[49m[43m([49m[43mplot_width[49m[38;5;241;43m=[39;49m[38;5;241;43m850[39;49m[43m,[49m[43m [49m[43mplot_height[49m[38;5;241;43m=[39;49m[38;5;241;43m300[39;49m[43m,[49m[43m [49m[43mtitle[49m[38;5;241;43m=[39;49m[38;5;124;43mf[39;49m[38;5;124;43m"[39;49m[38;5;124;43mDetrended Lightcurve (TIC[39;49m[38;5;132;43;01m{[39;49;00m[43mtic_id[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m)[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      3[0m [38;5;66;03m# Short cadence[39;00m
[1;32m      4[0m bfig[38;5;241m.[39mcircle(short_cad_lc[[38;5;124m"[39m[38;5;124mTIME[39m[38;5;124m"[39m], short_cad_lc[[38;5;124m"[39m[38;5;124mRAW_FLUX[39m[38;5;124m"[39m][38;5;241m/[39mnp[38;5;241m.[39mmedian(short_cad_lc[[38;5;124m"[39m[38;5;124mRAW_FLUX[39m[38;5;124m"[39m]), fill_color[38;5;241m=[39m[38;5;124m"[39m[38;5;124mblack[39m[38;5;124m"[39m,size[38;5;241m=[39m[38;5;241m2[39m, line_color[38;5;241m=[39m[38;5;28;01mNone[39;00m)

File [0;32m/usr/share/miniconda/lib/python3.10/site-packages/bokeh/plotting/_figure.py:190[0m, in [0;36mfigure.__init__[0;34m(self, *arg, **kw)[0m
[1;32m    188[0m [38;5;28;01mfor[39;00m name [38;5;129;01min[39;00m kw[38;5;241m.[39mkeys():
[1;32m    189[0m     [38;5;28;01mif[39;00m name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m names:
[0;32m--> 190[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_attribute_error_with_matches[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mnames[49m[43m [49m[38;5;241;43m|[39;49m[43m [49m[43mopts[49m[38;5;241;43m.[39;49m[43mproperties[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    192[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([38;5;241m*[39marg, [38;5;241m*[39m[38;5;241m*[39mkw)
[1;32m    194[0m [38;5;28mself[39m[38;5;241m.[39mx_range [38;5;241m=[39m get_range(opts[38;5;241m.[39mx_range)

File [0;32m/usr/share/miniconda/lib/python3.10/site-packages/bokeh/core/has_props.py:368[0m, in [0;36mHasProps._raise_attribute_error_with_matches[0;34m(self, name, properties)[0m
[1;32m    365[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m matches:
[1;32m    366[0m     matches, text [38;5;241m=[39m [38;5;28msorted[39m(properties), [38;5;124m"[39m[38;5;124mpossible[39m[38;5;124m"[39m
[0;32m--> 368[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124munexpected attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m!r}[39;00m[38;5;124m to [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m, [39m[38;5;132;01m{[39;00mtext[38;5;132;01m}[39;00m[38;5;124m attributes are [39m[38;5;132;01m{[39;00mnice_join(matches)[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mAttributeError[0m: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width
AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width

