Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
job = TAP_service.run_async("""
SELECT objID, RAMean, DecMean, nDetections, ng, nr, ni, nz, ny, gMeanPSFMag, rMeanPSFMag, iMeanPSFMag, zMeanPSFMag, yMeanPSFMag
FROM dbo.MeanObjectView
WHERE
CONTAINS(POINT('ICRS', RAMean, DecMean),CIRCLE('ICRS',187.706,12.391,.2))=1
AND nDetections > 1
  """)
TAP_results = job.to_table()
TAP_results
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mDALQueryError[0m                             Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m job [38;5;241m=[39m [43mTAP_service[49m[38;5;241;43m.[39;49m[43mrun_async[49m[43m([49m[38;5;124;43m"""[39;49m
[1;32m      2[0m [38;5;124;43mSELECT objID, RAMean, DecMean, nDetections, ng, nr, ni, nz, ny, gMeanPSFMag, rMeanPSFMag, iMeanPSFMag, zMeanPSFMag, yMeanPSFMag[39;49m
[1;32m      3[0m [38;5;124;43mFROM dbo.MeanObjectView[39;49m
[1;32m      4[0m [38;5;124;43mWHERE[39;49m
[1;32m      5[0m [38;5;124;43mCONTAINS(POINT([39;49m[38;5;124;43m'[39;49m[38;5;124;43mICRS[39;49m[38;5;124;43m'[39;49m[38;5;124;43m, RAMean, DecMean),CIRCLE([39;49m[38;5;124;43m'[39;49m[38;5;124;43mICRS[39;49m[38;5;124;43m'[39;49m[38;5;124;43m,187.706,12.391,.2))=1[39;49m
[1;32m      6[0m [38;5;124;43mAND nDetections > 1[39;49m
[1;32m      7[0m [38;5;124;43m  [39;49m[38;5;124;43m"""[39;49m[43m)[49m
[1;32m      8[0m TAP_results [38;5;241m=[39m job[38;5;241m.[39mto_table()
[1;32m      9[0m TAP_results

File [0;32m/usr/share/miniconda/lib/python3.10/site-packages/pyvo/dal/tap.py:302[0m, in [0;36mTAPService.run_async[0;34m(self, query, language, maxrec, uploads, **keywords)[0m
[1;32m    299[0m job [38;5;241m=[39m AsyncTAPJob[38;5;241m.[39mcreate(
[1;32m    300[0m     [38;5;28mself[39m[38;5;241m.[39mbaseurl, query, language, maxrec, uploads, [38;5;28mself[39m[38;5;241m.[39m_session, [38;5;241m*[39m[38;5;241m*[39mkeywords)
[1;32m    301[0m job [38;5;241m=[39m job[38;5;241m.[39mrun()[38;5;241m.[39mwait()
[0;32m--> 302[0m [43mjob[49m[38;5;241;43m.[39;49m[43mraise_if_error[49m[43m([49m[43m)[49m
[1;32m    303[0m result [38;5;241m=[39m job[38;5;241m.[39mfetch_result()
[1;32m    304[0m job[38;5;241m.[39mdelete()

File [0;32m/usr/share/miniconda/lib/python3.10/site-packages/pyvo/dal/tap.py:958[0m, in [0;36mAsyncTAPJob.raise_if_error[0;34m(self)[0m
[1;32m    956[0m     msg [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_job[38;5;241m.[39merrorsummary[38;5;241m.[39mmessage[38;5;241m.[39mcontent
[1;32m    957[0m msg [38;5;241m=[39m msg [38;5;129;01mor[39;00m [38;5;124m"[39m[38;5;124m<No useful error from server>[39m[38;5;124m"[39m
[0;32m--> 958[0m [38;5;28;01mraise[39;00m DALQueryError([38;5;124m"[39m[38;5;124mQuery Error: [39m[38;5;124m"[39m [38;5;241m+[39m msg, [38;5;28mself[39m[38;5;241m.[39murl)

[0;31mDALQueryError[0m: Query Error: Error executing underlying query
DALQueryError: Query Error: Error executing underlying query

